/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dz.univjijel.informatique3l.abd.devoir.gui;

import dz.univjijel.informatique3l.abd.devoir.exemple.DonneesExemples;
import dz.univjijel.informatique3l.abd.devoir.model.Client;
import dz.univjijel.informatique3l.abd.devoir.model.Emprunt;
import dz.univjijel.informatique3l.abd.devoir.model.Livre;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * La fenêtre pour créer un emprunt.
 * @author Tarek Boutefara <t_boutefara@esi.dz>
 */
public class EmprunterGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUIEmprunter
     */
    public EmprunterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodeClient = new javax.swing.JLabel();
        txtCodeClient = new javax.swing.JTextField();
        lblCodeLivre = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtNumSeq = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblPrenom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        lblTitre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTitre = new javax.swing.JTextArea();
        lblAuteur = new javax.swing.JLabel();
        lblEdition = new javax.swing.JLabel();
        lblAnnee = new javax.swing.JLabel();
        txtAuteur = new javax.swing.JTextField();
        txtEdition = new javax.swing.JTextField();
        txtAnnee = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpruntsEnCours = new javax.swing.JTable();
        btnConfirmer = new javax.swing.JButton();
        btnFermer = new javax.swing.JButton();
        lblEmpruntsEnCours = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emprunter");
        setResizable(false);

        lblCodeClient.setText("Code Client :");

        txtCodeClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodeClientKeyReleased(evt);
            }
        });

        lblCodeLivre.setText("Code Exemplaire :");

        txtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtISBNKeyReleased(evt);
            }
        });

        lblNom.setText("Nom :");

        txtNom.setEditable(false);

        lblPrenom.setText("Prénom :");

        txtPrenom.setEditable(false);

        lblTitre.setText("Titre :");

        txtAreaTitre.setEditable(false);
        txtAreaTitre.setColumns(20);
        txtAreaTitre.setRows(5);
        jScrollPane1.setViewportView(txtAreaTitre);

        lblAuteur.setText("Auteur :");

        lblEdition.setText("Edition :");

        lblAnnee.setText("Année de Publication :");

        txtAuteur.setEditable(false);

        txtEdition.setEditable(false);

        txtAnnee.setEditable(false);

        tblEmpruntsEnCours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ISBN/N°", "Titre", "Date Emprunt"
            }
        ));
        jScrollPane2.setViewportView(tblEmpruntsEnCours);

        btnConfirmer.setText("Confirmer Emprunt");

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        lblEmpruntsEnCours.setText("Emprunts en cours :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAnnee)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodeClient)
                                    .addComponent(lblNom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPrenom, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtNom)
                                    .addComponent(txtCodeClient))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCodeLivre)
                                    .addComponent(lblTitre)))
                            .addComponent(lblAuteur)
                            .addComponent(lblEdition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumSeq))
                            .addComponent(jScrollPane1)
                            .addComponent(txtAuteur)
                            .addComponent(txtEdition)
                            .addComponent(txtAnnee))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpruntsEnCours)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirmer)
                .addGap(281, 281, 281))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(btnFermer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeClient)
                    .addComponent(txtCodeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodeLivre)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNom)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrenom)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuteur)
                    .addComponent(txtAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdition)
                    .addComponent(txtEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnee)
                    .addComponent(txtAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnConfirmer)
                .addGap(22, 22, 22)
                .addComponent(lblEmpruntsEnCours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFermer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
       dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void txtCodeClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeClientKeyReleased
        if(!txtCodeClient.getText().equals(""))
           detecterClient();
    }//GEN-LAST:event_txtCodeClientKeyReleased

    private void txtISBNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNKeyReleased
        if(!txtISBN.getText().equals(""))
            detecterLivre();
    }//GEN-LAST:event_txtISBNKeyReleased

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmer;
    private javax.swing.JButton btnFermer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnnee;
    private javax.swing.JLabel lblAuteur;
    private javax.swing.JLabel lblCodeClient;
    private javax.swing.JLabel lblCodeLivre;
    private javax.swing.JLabel lblEdition;
    private javax.swing.JLabel lblEmpruntsEnCours;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTable tblEmpruntsEnCours;
    private javax.swing.JTextField txtAnnee;
    private javax.swing.JTextArea txtAreaTitre;
    private javax.swing.JTextField txtAuteur;
    private javax.swing.JTextField txtCodeClient;
    private javax.swing.JTextField txtEdition;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumSeq;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables

    /**
     * Permet de détecter le livre et de remplir les champs
     * des informations automatiquement.
     */
    private void detecterLivre() {
        String ISBN = txtISBN.getText();
        List<Livre> livres = DonneesExemples.getLivres();
        
        for (int i = 0; i < livres.size(); i++) {
            Livre l = livres.get(i);
            if(l.getISBN().equals(ISBN)){
                txtAreaTitre.setText(l.getTitre());
                txtAuteur.setText(l.getTitre());
                txtEdition.setText(l.getEdition());
                txtAnnee.setText(l.getAnneePublication() + "");
            }
        }
    }
    
    /**
     * Permet de détecter le client et de remplir les champs
     * des informations automatiquement.
     * Cette méthode n'est pas optimisée vu la taille des données qui ne 
     * nécessite pas une optimisation particulière.
     * @throws NumberFormatException 
     */
    private void detecterClient() throws NumberFormatException {
        while(((DefaultTableModel)tblEmpruntsEnCours.getModel()).getRowCount() > 0)
            ((DefaultTableModel)tblEmpruntsEnCours.getModel()).removeRow(0);
        txtNom.setText("");
        txtPrenom.setText("");
        
        int codeClient = Integer.parseInt(txtCodeClient.getText());
        List<Client> clients = DonneesExemples.getClients();
        for (int i = 0; i < clients.size(); i++) {
            Client c = clients.get(i);
            if(c.getNum() == codeClient){
                txtNom.setText(c.getNom());
                txtPrenom.setText(c.getPrenom());
                
                List<Emprunt> emprunts = DonneesExemples.getEmprunts();
                for (int j = 0; j < emprunts.size(); j++) {
                    Emprunt e = emprunts.get(j);
                    if(e.getNum() == codeClient && e.getRetour() == null){
                        
                        List<Livre> livres = DonneesExemples.getLivres();
                        for (int k = 0; k < livres.size(); k++) {
                            Livre l = livres.get(k);
                            
                            if(l.getISBN().equals(e.getISBN())){
                                ((DefaultTableModel)tblEmpruntsEnCours.getModel()).addRow(new String[]{l.getISBN()+"/"+e.getnSequentiel(), l.getTitre(), e.getEmprunt().toString()});
                            }
                            
                        }  
                    }
                }
            }
        }
    }
}
