/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dz.univjijel.informatique3l.abd.devoir.gui;

/**
 *
 * @author Tarek Boutefara <t_boutefara@esi.dz>
 */
public class MainGUI extends javax.swing.JFrame {

    EmprunterGUI egui;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        menuItemQuitter = new javax.swing.JMenuItem();
        menuGestLivres = new javax.swing.JMenu();
        menuGestClients = new javax.swing.JMenu();
        menuGestEmprunts = new javax.swing.JMenu();
        menuItemEmprunter = new javax.swing.JMenuItem();
        menuAide = new javax.swing.JMenu();
        menuItemAPropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de la Bibliothèque");

        menuFichier.setText("Fichier");

        menuItemQuitter.setText("Quitter");
        menuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuitterActionPerformed(evt);
            }
        });
        menuFichier.add(menuItemQuitter);

        menuBar.add(menuFichier);

        menuGestLivres.setText("Gestion des Livres");
        menuBar.add(menuGestLivres);

        menuGestClients.setText("Gestion des Clients");
        menuBar.add(menuGestClients);

        menuGestEmprunts.setText("Gestion des Emprunts");

        menuItemEmprunter.setText("Emprunter");
        menuItemEmprunter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmprunterActionPerformed(evt);
            }
        });
        menuGestEmprunts.add(menuItemEmprunter);

        menuBar.add(menuGestEmprunts);

        menuAide.setText("Aide");

        menuItemAPropos.setText("A Propos");
        menuAide.add(menuItemAPropos);

        menuBar.add(menuAide);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemQuitterActionPerformed

    private void menuItemEmprunterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmprunterActionPerformed
        if(egui == null){
            egui = new EmprunterGUI();
            egui.setVisible(true);
        }else{
            egui.setVisible(true);
        }
    }//GEN-LAST:event_menuItemEmprunterActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAide;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenu menuGestClients;
    private javax.swing.JMenu menuGestEmprunts;
    private javax.swing.JMenu menuGestLivres;
    private javax.swing.JMenuItem menuItemAPropos;
    private javax.swing.JMenuItem menuItemEmprunter;
    private javax.swing.JMenuItem menuItemQuitter;
    // End of variables declaration//GEN-END:variables
}
